# Generated by Django 2.2.24 on 2022-05-24 08:04

from django.db import migrations


def fill_owners_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, _ = Owner.objects.get_or_create(
            name=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        )
        flat.owners.set([owner])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20220524_1036'),
    ]

    operations = [
        migrations.RunPython(fill_owners_flats)
    ]
